### ISSUE TITLE
GeoJSONToGeoPackage is undefined

### ISSUE THREAD

**Issue by achmadk** [ngageoint/geopackage-js#148]
I want to convert GeoPackage data into GeoJSON with [your app](https://ngageoint.github.io/geopackage-js/). I have uploaded [Indonesia GeoPackage](https://biogeo.ucdavis.edu/data/gadm3.6/gpkg/gadm36_IDN_gpkg.zip) from GADM, which has around 450MB file size uncompressed. After its feature table is loaded, I want to download layer as GeoJSON. I have click that link but unfortunately I have error `GeoJSONToGeoPackage is undefined` in log console.

**Comment by danielbarela** [comment]
I will look into and fix it up today.

**Comment by danielbarela** [comment]
OK, I fixed the issue with the GeoJSON converter and deployed the corrected version.  However, your GeoPackage is very big with tables that contain a lot of data.  We do not run on a server so everything takes place in the browser, including the data conversion.  In order to download the file, we first convert the GeoJSON into a blob and use FileSaver.js to download the file to the computer.  This blob has a size limit and your very large table exceeds that.  I was able to download every table except the largest one.  I will have to continue to find a different way to save the data from the browser for large tables.
