### ISSUE TITLE
rivers.gpkg issue

### ISSUE THREAD

**Issue by rghosh0** [ngageoint/geopackage-js#26]
I believe the rivers.gpkg file in test/fixtures has a problem.  For the tile pyramid, the srs_id is 4326 in gpkg_contents but 3857 in gpkg_tile_matrix_set, whereas the OGC spec says they must be the same value and it looks like that would be 3857.

**Comment by bosborn** [comment]
I believe that is legal from what I can find in the spec.  Can you provide a reference number from the GeoPackage spec that you are referring to?

Both the Contents and the Tile Matrix Set have a foreign key to the SRS table.  The Tile Matrix Set also has a foreign key to the Contents table.  Forcing those values to be the same would cause redundancy in the spec.

The Contents defines the informative bounds and the Tile Matrix Set defines the tile pyramid bounds.  The data within each of those is projected according to the SRS each contains.

Here are some parts of the spec that seem relevant:

1.1.3. Contents
...
The bounding box (min_x, min_y, max_x, max_y) provides an informative bounding box (not necessarily minimum bounding box) of the content. If the srs_id column value references a geographic coordinate reference system (CRS), then the min/max x/y values are in decimal degrees; otherwise, the srs_id references a projected CRS and the min/max x/y values are in the units specified by that CRS.

Requirement 16
Values of the gpkg_contents table srs_id column SHALL reference values in the gpkg_spatial_ref_sys table srs_id column.


2.2. Tiles
...
2.2.2. Contents
...
Requirement 34
The gpkg_contents table SHALL contain a row with a data_type column value of “tiles” for each tile pyramid user data table or view.

2.2.6. Tile Matrix Set
...
The gpkg_tile_matrix_set table or updateable view defines the spatial reference system (srs_id) and the maximum bounding box (min_x, min_y, max_x, max_y) for all possible tiles in a tile pyramid user data table.
...
Requirement 41
Values of the gpkg_tile_matrix_set srs_id column SHALL reference values in the gpkg_spatial_ref_sys srs_id column.

**Comment by rghosh0** [comment]
http://www.geopackage.org/spec/#_contents
1.1.3.1.1 Table Definition
_(Regarding the gpkg_contents table)_
...
`srs_id`  ... When data_type is tiles, SHALL also match `gpkg_tile_matrix_set.srs_id`

**Comment by bosborn** [comment]
Thanks for the reference.  I missed that hidden in the description field.  I'll confirm with the OGC GeoPackage group and we will adapt from there.

**Comment by bosborn** [comment]
It looks like that requirement might need to be corrected in the spec:
http://lists.opengeospatial.org/pipermail/geopackage/2016-July/000194.html

We'll keep this open till we confirm one way or the other.

**Comment by bosborn** [comment]
Fixed the [rivers.gpkg](https://github.com/ngageoint/GeoPackage/blob/gh-pages/examples/rivers.gpkg?raw=true) file to have a matching srs_id between the gpkg_contents and gpkg_tile_matrix_set tables.

Without much explanation, they decided to keep the srs matching statement in the contents table srs_id column description (opengeospatial/geopackage#233).  Since there is a foreign key from the contents, tile matrix set, and geometry columns, I'd still recommend relying on the srs id local to the data when reading values.
