### ISSUE TITLE
view mbtiles -not convert - no node.js express back-end just local view

### ISSUE THREAD

**Issue by techmavengeospatial** [ngageoint/geopackage-js#60]
It would be great to view mbtiles in the browser without any server side conversion.
That way you can use geopackage-js with some other leaflet plugins and maybe ionic framework and create some mobile apps that allow for offline and online

**Comment by danielbarela** [comment]
This library does convert MBTiles to a GeoPackage in the browser without node, which is then displayed on the map.  Can you clarify how this does not meet your request?

**Comment by techmavengeospatial** [comment]
First off awesome work! Amazing what  you've done! Can it just be run from a folder? I extracted the zip file from github and running it locally (not on a web server) I picked a very small data set 25mb mbtiles and it says creating table "tiles" and the thing spins but I don't see any other progress.  I guess to clarify just display immediately on the map.  I see that someone build a mobile app based on this library. Using Apache Cordova https://itunes.apple.com/us/app/**gpkg-mobile/**id1134154542?mt=8

**Comment by danielbarela** [comment]
I added in some extra progress information as it is processing.  Every 5% of progress will be updated on the GUI.

As far as automatically displaying the data on the map, I made the decision to not do that because some GeoPackages are large and contain many layers.  This page is really just a demo of the geopackage-js framework so having the users turn on layers manually after the GeoPackage is loaded was acceptable.

Good find on that app, great to see that others are getting use out of this library.
