### ISSUE TITLE
npm install errors

### ISSUE THREAD

**Issue by gotnull** [ngageoint/geopackage-js#91]
![screen shot 2017-08-01 at 3 24 32 pm](https://user-images.githubusercontent.com/578908/28810533-969d5f80-76cd-11e7-90da-7987ef669e7e.png)

**Comment by gotnull** [comment]
ATT: https://github.com/Automattic/node-canvas/issues/225#issuecomment-155672545

**Comment by gotnull** [comment]
I'm running macOS Sierra 10.12.6 (16G29)

**Comment by gotnull** [comment]
I got a bit further by executing:

`xcode-select --install`
`brew unlink cairo`
`brew uninstall cairo`
`brew install cairo`
`npm install canvas`

I wouldn't actually be able to tell you where exactly it allowed me to go further in the installation process though.

I now get the following error:

![screen shot 2017-08-01 at 3 36 18 pm](https://user-images.githubusercontent.com/578908/28810863-5635f9a0-76cf-11e7-8ea5-0699ee9d09be.png)

**Comment by gotnull** [comment]
Proper installation documentation would be great.

**Comment by danielbarela** [comment]
I have removed the dependency on image-diff which should clear up the need for any of the node-canvas stuff.  To install, you simply need to npm install and that should install everything you need.  You do not need to globally install anything.  Please let me know if this new version still does not work.  The uglifyjs bug you are seeing was fixed with the new version which is also included in this update.
